language: python
python:
  - "3.6"
install:
  - pip install python-coveralls nosexcover
  - pip install -r requirements_tests.txt
  - snips-nlu download-all-languages
script:
  - python -m nose --with-doctest --with-xcoverage --cover-package=TEMPLATE_SKILL_PACKAGE
